const emailTypes = {
  PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
  PASSWORD_RECOVERY_LINK: "PASSWORD_RECOVERY_LINK",
  EMAIL_REGISTER_CONFIRMATION: "EMAIL_REGISTER_CONFIRMATION",
  FORM_CONTACT: "FORM_CONTACT",
  FORM_CONTACT_FOR_USER: "FORM_CONTACT_FOR_USER",
};

module.exports = emailTypes;
