const emailTypes = {
  PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
  PASSWORD_RECOVERY_LINK: "PASSWORD_RECOVERY_LINK",
  EMAIL_REGISTER_CONFIRMATION: "EMAIL_REGISTER_CONFIRMATION",
};

module.exports = emailTypes;
